### ISSUE TITLE
官网进不去啊

### ISSUE THREAD

**Issue by cybytess** [bytfr/pywin10ui#1]
![Screenshot_20220102_211000.jpg](https://user-images.githubusercontent.com/87681509/147876861-a18f1093-8aa6-4fd8-a1f8-f247482f096c.jpg)

**Comment by bytfr** [comment]
官网由于资金原因，没有续费服务器，目前内容都只会在github更新，如果资金在充足的情况下会考虑续费服务器的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bytfr/pywin10ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月2日(星期天) 晚上9:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[bytfr/pywin10ui] 官网进不去啊 (Issue #1)





 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cybytess** [comment]
**感谢回复**
其实可以试一下Github Page
