### ISSUE TITLE
依赖了easygui但setup.py还有帮助文档里都没有写

### ISSUE THREAD

**Issue by cybytess** [bytfr/pywin10ui#2]
<img width="852" alt="image" src="https://user-images.githubusercontent.com/87681509/149938708-d9eea899-6d10-4994-83da-9bcf08554396.png">
pip安装时应该一起把easygui安进去

**Comment by bytfr** [comment]
谢谢提醒


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bytfr/pywin10ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月18日(星期二) 晚上8:38
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[bytfr/pywin10ui] 依赖了easygui但setup.py还有帮助文档里都没有写 (Issue #2)





 

 pip安装时应该一起把easygui安进去 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cybytess** [comment]
哦，setup.py可不可以放在仓库根目录呢，这样可能要好一点吧。

**Comment by bytfr** [comment]
已经放了，我还要更新一下版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月18日(星期二) 晚上8:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bytfr/pywin10ui] 依赖了easygui但setup.py还有帮助文档里都没有写 (Issue #2)





 
哦，setup.py可不可以放在仓库根目录呢，这样可能要好一点。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cybytess** [comment]
感谢
